#!/bin/bash
mkdir -p /home/ubuntu/test/vol/cortex
git clone https://github.com/TheHive-Project/Cortex-Analyzers.git /home/ubuntu/test/vol/cortex
alias cortexDir="cd /home/ubuntu/test/vol/cortex"
cortexDir
pwd
apt update && apt install -y python3-pip && rm -rf /var/lib/apt/lists/*
pip3 install ldap3 requests
for I in $(find analyzers -name 'requirements.txt'); do pip3 install -r $I || true; done
